blank_issues_enabled: false

contact_links:
  - name: "Question â†’ Q&A at GitHub Discussions"
    url: "https://github.com/valentjn/vscode-ltex/discussions?discussions_q=category%3AQ%26A"
    about: "Got a question about LTeX, not a bug report or feature request? Ask here for help!"
  - name: "Website/Documentation of LTeX"
    url: "https://valentjn.github.io/ltex/"
    about: "Browse through the official documentation of LTeX."
